config/routes.rb
SampleApp::Application.routes.draw do

  get "requests/new"

  get "sessions/new"

  resources :users
  resources :requests
  resources :pages
  resources :services
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  
  match '/forgot',  			:to => 'users#forgot'
  match '/reset/:reset_password_code',  	:to => 'users#reset'
  match '/verify-request/:verification_code',  	:to => 'requests#verify'
  match '/verify-user/:verification_code',  	:to => 'users#verify'
  
  match ':permalink', :to => 'pages#show'
  

  root :to => 'pages#home'

end

app/views/pages/_jurisdiction.html.erb
<% jurisdiction_display = "India" %>
<% if @agency.jurisdiction == 1 %>
<%		jurisdiction_display = "City of " + @agency.city %>
<% elsif @agency.jurisdiction == 2 %>
<% 		jurisdiction_display = "State of " + @agency.state %>
<% end %>
Government of <%= jurisdiction_display %> <br/>

app/views/pages/_page.html.erb
<li>
  <%= link_to page.orgname, page %>
  <% if signed_in? && current_user.admin? %>
  | <%= link_to "delete", page, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{page.orgname}" %>
  <% end %>
  
</li>

app/views/pages/_service_form.html.erb
  <div class="field">
    <%= f.label "Service" %>
    <%= f.text_field :service_name %>  
  </div>
  <div class="field">
  	<%= f.label "URL" %>
    <%= f.text_field :service_url %>  
  </div>

app/views/pages/about.html.erb
<h1>About rgov</h1>
<p class="emphasis">
  We connect citizens of India with their government <br/>
  <br/>
  <strong>What we do?</strong><br/>
  * We enable citizens to find useful information about their government<br/>
  * We enable citizens to request the government for public information<br/>
  * We enable government to communicate with their citizens directly<br/>
  <br/>
  <strong>What we do not do?</strong><br/>
  * We do not promote anarchy, we think a healthy functioning government is very important<br/>
  * We do not take responsibility for how citizens and governments choose to use our platform<br/>  
  <br/>
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/edit.html.erb
<h1>Edit agency</h1>

<%= form_for(@agency) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :orgname, "Department" %><br />
    <%= f.text_field :orgname %>
  </div>
  <div class="field">
    <%= f.label :jurisdiction %><br />
    <%= f.select( :jurisdiction, { "City agency" => "1", "State agency" => "2", "National agency" => "3"}) %>
  </div>
  <div class="field">
    <%= f.label :street1, "Address" %><br />
    <%= f.text_field :street1 %>
  </div>
  <div class="field">
    <%= f.label :street2, "Address (continued)" %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :district %><br />
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
	<%= f.select( :state, ApplicationHelper::STATES_LIST, :include_blank => "Choose..." ) %>
  </div>
  <div class="field">
    <%= f.label :pin %><br />
    <%= f.text_field :pin %>
  </div>
  <div class="field">
    <%= f.label :external_url, 'Website' %><br />
    <%= f.text_field :external_url %>
  </div> 
  <div class="field">
    <%= f.label :leader, 'Agency leader' %><br />
    <%= f.text_field :leader %>
  </div> 
  <div class="field">
    <%= f.label :leader_title, 'Designation' %><br />
    <%= f.text_field :leader_title %>
  </div> 
  <div class="field">
    <%= f.label :budget, 'Annual budget (in Rs crores)' %><br />
    <%= f.text_field :budget %>
  </div>   
  <div class="field">
    <%= f.label :budget_year, 'Budget year (Example: 2010-11)' %><br />
    <%= f.text_field :budget_year %>
  </div>   
  <div class="field">
    <%= f.label :rti_payee, "RTI fee must be paid to" %><br />
    <%= f.text_field :rti_payee %>
  </div>
  <div class="field">
    <%= f.label :rti_payable_at, "RTI fee must be payable at (leave blank if same as address)" %><br />
    <%= f.text_field :rti_payable_at %>
  </div>  
  <div class="field">
    <%= f.label :function %><br />
    <%= f.text_area :function %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/pages/help.html.erb
<h1>Help</h1>

<p>
  We don't have the resources to provide support. 
  However, you can email us at info at yougovt dot in and we will try to help you. 
  No guarantees. 
</p>

app/views/pages/home.html.erb
<script type="text/javascript">
$(function() {

 	// Below is the name of the textfield that will be autocomplete   
    $('#query').autocomplete({
 		// This shows the min length of charcters that must be typed before the autocomplete looks for a match.
    	minLength: 1,
 		// This is the source of the auocomplete suggestions. In this case a list of agency names from the pages controller, in JSON format.
    	source: '<%= pages_path(:json) %>',
  		// This updates the textfield when you move the updown the suggestions list, with your keyboard. 
  		// In our case it will reflect the same value that you see in the suggestions which is the page.orgname.
    	focus: function(event, ui) {
    		$('#query').val(ui.item.page.orgname);
        	return false;
    	},
 		// Once a value in the drop down list is selected, do the following:
        select: function(event, ui) {
 			// place the page.orgname value into the textfield called 'query'
            $('#query').val(ui.item.page.orgname);
 			// and place the page.id into the hidden textfield called 'link_query'. 
        	$('#link_query').val(ui.item.page.id);
        	var agencyURL = "pages/" + ui.item.page.id;
        	window.location.href = agencyURL;
            return false;
        }
    })
 	// The below code is straight from the jQuery example. It formats what data is displayed in the dropdown box, and can be customized.
    .data( "autocomplete" )._renderItem = function( ul, item ) {
            return $( "<li></li>" )
            .data( "item.autocomplete", item )
 			// For now which just want to show the page.orgname in the list.
            .append( "<a href=\"pages/" + item.page.id + "\">" + item.page.orgname + "</a>" )
            .appendTo( ul );
        };
    });
</script>


<h1 align="center">Search government offices</h1>

<p align="center">
  <input class="textbox" id="query"/>
  <input id="link_query" name="link[query]" type="hidden"/>
</p>


<p align="center">Didn't find the information you were looking for anywhere?</p>

<%= link_to "File an RTI", new_request_path, :class => "signup_button round" %>
<br/>
<p class="small" align="center">RTI means Right To Information. The Government of India created the Right To Information Act 
in 2005 to enable all citizens of India to request for information from government authorities.</p>

<h1 align="center" style="font-family: 'Pacifico', arial, serif;">
	<a href = "http://blog.rgov.in/2011/03/14/make-government-work-for-you/">govTalk</a>
</h1>
<p align="center" class="small">Learn how to navigate some common government processes</p>

app/views/pages/index.html.erb
<h1>Agencies in the rgov database</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @pages %>
</ul>

<%= will_paginate %>

app/views/pages/new.html.erb
<h1>Add a government agency or government supported company</h1>

<%= form_for(@agency) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :orgname, "Department" %><br />
    <%= f.text_field :orgname %>
  </div>
  <div class="field">
    <%= f.label :jurisdiction %><br />
    <%= f.select( :jurisdiction, { "City agency" => "1", "State agency" => "2", "National agency" => "3"}) %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>  
  <div class="field">
    <%= f.label :function %><br />
    <%= f.text_area :function %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/pages/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1><%= @agency.orgname %></h1>
      
      <%= render 'jurisdiction' %>
      
      <div id="external_link">
      <% if @agency.external_url? %>
      	<%=	link_to @agency.external_url, @agency.external_url %>
      <% else %> 
      	<%= link_to 'Add URL', edit_page_path(@agency) %>
      <% end %> <br><br />
      </div>
      
      
      <h3>Functions:</h3>
      <%= simple_format(@agency.function) %>
      <br/>
      
      <div>
      <h3>Services:</h3>
	  <% unless @existing_services.empty? %>
	  	<table id = "services" class="services" summary="User services">
          	<%= render @existing_services %>
        </table>
      <% end %>
      </div>
      
      <% if @agency.street1 %>
      <div>   
      <h3>Address:</h3>
	  <%= @agency.street1 %><br/>
	  <%= @agency.street2 if @agency.street2 %><br/>
   	  <%= @agency.city %> 
   	  <%= ", #{@agency.district}" unless @agency.district.empty? %>
   	  <%= ", #{@agency.state}" %><br/>
   	  PIN: <%= @agency.pin %>
   	  <br/><br/>
   	  </div>
   	  <% end %>
      
		
	  <h3>Add a service:</h3>
      <% form_for @service, :remote => true, :html => { :id => "add_service_form" } do |f| %>
      	<%= f.hidden_field :page_id, :value => @agency.id %>
      	<label for="name">Service:</label><br />
      	<%= f.text_field :name %><br />
      	<label for="external_link">Link:</label><br />
      	<%= f.text_field :external_link %><br />
      	<label for="desc">Description (optional):</label><br />
      	<%= f.text_area :desc %>
		<p><%= submit_tag 'Add Service' %></p>
	  <% end %>
		
      <%= link_to 'Edit page', edit_page_path(@agency) %>
      
      
    </td>
    <td class="sidebar round">
		<h3>Quick Facts</h3>
		<% if (@agency.leader) %>
			<strong>
			<% if(@agency.leader_title) %>
				<%= @agency.leader_title %> 
			<% else %>
				Leader
			<% end %>
			</strong><br />
			<%= @agency.leader %><br />
		<% else %>
			<%= link_to 'Add leader', edit_page_path(@agency) %><br />
		<% end %>
		
		<% if (@agency.budget) %>
			<strong>Budget</strong><br />
			Rs <%= (@agency.budget) %> cr<br />
		<% else %>
			<%= link_to 'Add budget', edit_page_path(@agency) %><br />
		<% end %>
		<strong>RTI options</strong><br />
    </td>
  </tr>
</table>