config/routes.rb
SampleApp::Application.routes.draw do

  get "requests/new"

  get "sessions/new"

  resources :users
  resources :requests
  resources :pages
  resources :services
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  
  match '/forgot',  			:to => 'users#forgot'
  match '/reset/:reset_password_code',  	:to => 'users#reset'
  match '/verify-request/:verification_code',  	:to => 'requests#verify'
  match '/verify-user/:verification_code',  	:to => 'users#verify'
  
  match ':permalink', :to => 'pages#show'
  

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "View all departments", pages_path %></li>
      <li><%= link_to "Add a department", new_page_path %></li>
      <li><%= link_to "Sign up", new_user_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_ga.html.erb
<% if Rails.env.production? %>
    <!-- Google analytics code -->
	<script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-21979728-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.10.custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery-1.4.4.min.js', 'jquery-ui-1.8.10.custom.min.js' %>  
  	<%= render 'layouts/ga' %>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="container">
		<%= render 'layouts/header' %>
      	<section class="round">
        	<% flash.each do |key, value| %>
          		<%= content_tag(:div, value, :class => "flash #{key}") %>
        	<% end %>
        	<%= yield %>
      	</section>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>